apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: "[Platform] Project"
  description: Create a new sre-platform's project 
spec:
  owner: team-a
  type: platform-core-4

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Name & Ownership
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the project
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner team of the project
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Google Cloud Integration
      required:
        - gcpNonProd
        - gcpProd
      properties:
        gcpNonProd:
          title: GCP NonProd Project ID
          type: string
          description: The ID of the non-production Google Cloud project
          ui:options:
            rows: 5
        gcpProd:
          title: GCP Prod Project ID
          type: string
          description: The ID of the production Google Cloud project
          ui:options:
            rows: 5
    - title: Azure Devops Integration
      properties:
        useExistentAzdevopsProject:
          title: Link an Existent Azure Devops project
          type: boolean
          description: Whether use an existent Azure Devops project instead of create a new one
        azdevopsProjectProcess:
          title: Azure Devops project process
          type: string
          description: The name of process to be used in the new AzureDevOps Project to be created
          enum: ["CMMI", "agile", "scrum", "basic", "kanban"]
      dependencies:
        useExistentAzdevopsProject:
          oneOf:
            - properties:
                useExistentAzdevopsProject:
                  boolean: true
                azdevopsProject:
                  title: Azure Devops project
                  type: string
                  description: The name of an existing AzureDevOps Project to linked to the Platform Project
                  ui:options:
                    rows: 5
                  # ui:widget:
                  #   hidden: ${{ parameters.useExistentAzdevopsProject }}
              required: ["azdevopsProject"]
      # dependencies:
      #   useExistentAzdevopsProject: ["azdevopsProject"]

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: debug
      name: Debug
      action: debug:log
      input:
        listWorkspace: true
    # - id: fetch-base
    #   name: Fetch Base
    #   action: fetch:template
    #   input:
    #     url: ./template
    #     values:
    #       name: ${{ parameters.name }}
    #       owner: ${{ parameters.owner }}

    # - id: fetch-docs
    #   name: Fetch Docs
    #   action: fetch:plain
    #   input:
    #     targetPath: ./community
    #     url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  # output:
  #   remoteUrl: ${{ steps.publish.output.remoteUrl }}
  #   entityRef: ${{ steps.register.output.entityRef }}
